development:
  adapter: postgresql
  database: trainz_development
  host: localhost
  port: 5432
  pool: 5
  
test:
  adapter: postgresql
  database: trainz_test
  host: localhost
  port: 5432
  pool: 5
